version: "3"
services:
  # Service names
  app:
    # Dockerfile location
    container_name: "map_app_api"
    build:
      context: ..
      dockerfile: ./.devcontainer/images/python/Dockerfile
    restart: always
    tty: true
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env.development
    volumes:
      - ..:/workspace
    # default command so things don't shut down after the process ends.
    ports:
      - 8000:8000
    expose:
      - "8000"
    networks:
      - local-net
  mysql:
    container_name: "map_app_db"
    build:
      context: ./images/mysql
      dockerfile: ./Dockerfile
    # M1マック向けのplatform設定
    platform: linux/x86_64
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env.development
    ports:
      - 3306:3306
    expose:
      - "3306"
    networks:
      - local-net
networks:
  local-net:
    driver: bridge
volumes:
  db-data:
    driver: local
